### ISSUE TITLE
in example notebook feature results differ when they are computed two times in a row

### ISSUE THREAD

**Issue by anilbey** [BlueBrain/BluePyEfe#107]
This cell (code block of ipynb) of the `examples/example_of_extraction.ipynb` computes the efeatures. When you run it once, spikecount is 9.0. When you run it twice, spikecount is 62.0. Looks like some state remains and affects the consecutive run. 
```python
interesting_efeatures = [
    'Spikecount',
    'mean_frequency',
    'ISI_CV',
    'AP1_amp',
    'AP_width'
]

cell.extract_efeatures(
    protocol_name='IDRest', 
    efeatures=interesting_efeatures
)

pprint(cell.recordings[0].efeatures)

```
First run
```
{'AP1_amp': 66.47175655411542,
 'AP_width': 1.555555555554507,
 'ISI_CV': 0.4542672780653756,
 'Spikecount': 9.0,
 'mean_frequency': 4.6922655822351}
```
Second run
```
{'AP1_amp': 69.72160224665397,
 'AP_width': 1.533870967740832,
 'ISI_CV': 0.07743046471280614,
 'Spikecount': 62.0,
 'mean_frequency': 31.352718078403036}
```
Third and fourth runs are the same as second run.

**Comment by DrTaDa** [comment]
I cannot reproduce the issue. Do you have a minimum working example ?

Maybe you accidentally ran a further cell which do change what is inside "cell" ?

**Comment by anilbey** [comment]
Ah yes, that's correct. The other code in the notebook changed the cell and then the features are also changed of course. Closing this false-positive issue :)
