### ISSUE TITLE
Add linting/black

### ISSUE THREAD

**Issue by arnaudon** [BlueBrain/BluePyEfe#133]
The CI here does not have any code style requirements, which would be good to have I presume

**Comment by anilbey** [comment]
There is actually `pycodestyle` in` tox`. But yes a more thorough linter tool like `pylint` can be useful. What do you say @DrTaDa ?

https://github.com/BlueBrain/BluePyEfe/blob/master/tox.ini#L32
`style: pycodestyle --ignore=E402,W503,W504,E203,E501,E722,W605 bluepyefe`.

**Comment by arnaudon** [comment]
this is very basic, it does not even check if there are 2 lines between functions, etc...

**Comment by DrTaDa** [comment]
Sure. Let's go for it :)

**Comment by arnaudon** [comment]
If I do that, are you guys reading to solve the avalanche of pylint complaints? I won't have the energy to do that I think...

**Comment by wvangeit** [comment]
Yeah, that was my worry too. I don't think this is a priority at the moment.
It will also mess up the entire history tracking.

**Comment by arnaudon** [comment]
haha, here is it: https://github.com/BlueBrain/BluePyEfe/pull/136
