### ISSUE TITLE
Use BBP doc template

### ISSUE THREAD

**Issue by wvangeit** [BlueBrain/BluePyEfe#149]
@anilbey or @AurelienJaquier , could you make sure this package would use the BBP doc template (as is done for bluepyopt etc).
The reason why I ask is because the github README doesn't seem to be used in the doc. Thx.

**Comment by AurelienJaquier** [comment]
Done. Now the docs use bbp style and the readme.
I'll close this issue now. Don't hesitate to re-open it needed.
