### ISSUE TITLE
Suggestion: tagging BPE2 branch to count from version 2.0.0

### ISSUE THREAD

**Issue by anilbey** [BlueBrain/BluePyEfe#70]
Currently the version on the `master` branch is `0.3.104` and the `BPE2` branch is `0.3.180`.
However some time ago `BPE2` branch also had a version of `bluepyefe` that was `0.3.104`.

Some versions of `bluepyefe` (e.g.  `0.3.95`) have different implementations in both `master` and `BPE2` branches.

This confuses me since I have use the `master` branch in some projects and `BPE2` branch in some other. 
When I need to work on a workflow that I ran some time ago, I can see the bluepyefe version that I had used but that does not tell me if I used the `BPE2` branch or the `master` branch.

To avoid this confusion, does it make sense if we tag the `BPE2` branch to start from version 2.0.0?
The version and the code-base will have a one-to-one correspondence this way.

E.g.
```
> git co BPE2
Switched to branch 'BPE2'
Your branch is up to date with 'origin/BPE2'. 
> python setup.py --version
0.3.180
```

```
> git co master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
> python setup.py --version
0.3.104
```

**Comment by DrTaDa** [comment]
Sure ! I am not sure how to do it though, do you know ?

**Comment by anilbey** [comment]
Yes we need to create a new commit on the BPE2 branch, tag that commit with 2.0.0 and then push the commit and the tag.

**Comment by anilbey** [comment]
Shall I do it?

**Comment by DrTaDa** [comment]
Yes please :)

**Comment by anilbey** [comment]
Voilà :)

```
> git co BPE2
Already on 'BPE2'
Your branch is up to date with 'origin/BPE2'.
> python setup.py --version
2.0.0

```

```
> git co master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
> python setup.py --version
0.3.104
```
