### ISSUE TITLE
Add documentation link on the About section

### ISSUE THREAD

**Issue by stefanoantonel** [BlueBrain/BluePyEfe#79]
Can you add a link to the official documentation to the right panel in the About section as we have in [Snap](https://github.com/BlueBrain/snap)

![Screenshot 2022-07-28 at 13 17 01](https://user-images.githubusercontent.com/4954312/181492744-ecfc80b5-78ab-440e-a306-0c000a742e52.png)

**Comment by wvangeit** [comment]
Done
