### ISSUE TITLE
BPE2 in_data is not defined for _nwb_reader_BBP

### ISSUE THREAD

**Issue by anilbey** [BlueBrain/BluePyEfe#86]
An undefined variable is accessed in `_nwb_reader_BBP`.

https://github.com/BlueBrain/BluePyEfe/blob/694d381eff28d6d48b93461497f959e25fc9998f/bluepyefe/reader.py#L273

**Comment by DrTaDa** [comment]
On it

**Comment by anilbey** [comment]
Thanks!
